Testable.Components <- list(basic.plsda = c("Comp1", "Comp2"),
                            basic.splsda = c("Comp1", "Comp2"),
                            basic.mint.plsda = c("Comp1"),
                            basic.mint.splsda = c("Comp1"),
                            basic.block.plsda = c("miRNA", "mRNA", "proteomics"),
                            basic.block.splsda = c("miRNA", "mRNA", "proteomics"),
                            srbct.splsda = c("Comp1", "Comp2"),
                            newdata.splsda = c("Comp1", "Comp2"),
                            multilevel.splsda = c("Comp1", "Comp2"),
                            roc.comp.splsda = c("Comp1", "Comp2"),
                            roc.study.mint.splsda = c("Comp2"),
                            roc.block.splsda = c("miRNA", "mRNA", "proteomics"),
                            study.test.mint.splsda = c("Comp2")
)

Ground.Truths <- list(basic.plsda = list(Comp1 = structure(c(0.863, 2.473e-05), 
                                                           .Dim = 1:2, 
                                                           .Dimnames = list("AF vs BE", 
                                                                            c("AUC", "p-value"))), 
                                         Comp2 = structure(c(0.9981, 7.124e-09), 
                                                           .Dim = 1:2, 
                                                           .Dimnames = list("AF vs BE", c("AUC", "p-value")))),
                      basic.splsda = list(Comp1 = structure(c(0.9704, 4.623e-08), 
                                                            .Dim = 1:2, 
                                                            .Dimnames = list("AF vs BE", c("AUC", "p-value"))), 
                                          Comp2 = structure(c(0.9981, 7.124e-09), 
                                                            .Dim = 1:2, 
                                                            .Dimnames = list("AF vs BE", c("AUC", "p-value")))),
                      basic.mint.plsda = list(Comp1 = structure(c(0.993, 0.6361, 0.8258, 4.441e-16, 0.01658, 3.671e-10), 
                                                                .Dim = 3:2, 
                                                                .Dimnames = list(c("Fibroblast vs Other(s)", 
                                                                                   "hESC vs Other(s)", 
                                                                                   "hiPSC vs Other(s)"), 
                                                                                 c("AUC", "p-value")))),
                      basic.mint.splsda = list(Comp1 = structure(c(1, 0.7844, 0.8075, 2.22e-16, 5.496e-07, 3.3e-09), 
                                                                 .Dim = 3:2, 
                                                                 .Dimnames = list(c("Fibroblast vs Other(s)", 
                                                                                    "hESC vs Other(s)",
                                                                                    "hiPSC vs Other(s)"), 
                                                                                  c("AUC", "p-value")))),
                      basic.block.plsda = list(miRNA = list(comp1 = structure(c(0.9365, 0.5861, 0.9218, 0, 0.1453, 0), 
                                                                              .Dim = 3:2, 
                                                                              .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                 "Her2 vs Other(s)", 
                                                                                                 "LumA vs Other(s)"), 
                                                                                               c("AUC", "p-value"))), 
                                                            comp2 = structure(c(0.9494, 0.5856, 0.9257, 0, 0.1479, 0), 
                                                                              .Dim = 3:2, 
                                                                              .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                 "Her2 vs Other(s)", 
                                                                                                 "LumA vs Other(s)"), 
                                                                                               c("AUC", "p-value")))), 
                                               mRNA = list(comp1 = structure(c(0.9937, 0.6206, 0.9918, 0, 0.04144, 0), 
                                                                             .Dim = 3:2, 
                                                                             .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                "Her2 vs Other(s)", 
                                                                                                "LumA vs Other(s)"), 
                                                                                              c("AUC", "p-value"))), 
                                                           comp2 = structure(c(0.9962, 0.5725, 0.9893, 0, 0.2201, 0), 
                                                                             .Dim = 3:2, 
                                                                             .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                "Her2 vs Other(s)", 
                                                                                                "LumA vs Other(s)"), 
                                                                                              c("AUC", "p-value")))), 
                                               proteomics = list(comp1 = structure(c(0.9564, 0.6578, 0.9844, 0, 0.007614, 0), 
                                                                                   .Dim = 3:2, 
                                                                                   .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                      "Her2 vs Other(s)", 
                                                                                                      "LumA vs Other(s)"), 
                                                                                                    c("AUC", "p-value" ))), 
                                                                 comp2 = structure(c(0.9757, 0.6564, 0.9865, 0, 0.008164,0), 
                                                                                   .Dim = 3:2, 
                                                                                   .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                      "Her2 vs Other(s)", 
                                                                                                      "LumA vs Other(s)"), 
                                                                                                    c("AUC", "p-value"))))),
                      basic.block.splsda = list(miRNA = list(comp1 = structure(c(0.9549, 0.5642, 0.9232, 0, 0.2778, 0), 
                                                                               .Dim = 3:2, 
                                                                               .Dimnames = list(c("Basal vs Other(s)",
                                                                                                  "Her2 vs Other(s)", 
                                                                                                  "LumA vs Other(s)"), 
                                                                                                c("AUC", "p-value"))), 
                                                             comp2 = structure(c(0.9619, 0.8644, 0.9595, 0, 7.078e-10, 0), 
                                                                               .Dim = 3:2, 
                                                                               .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                  "Her2 vs Other(s)", 
                                                                                                  "LumA vs Other(s)"), 
                                                                                                c("AUC", "p-value")))), 
                                                mRNA = list(comp1 = structure(c(0.9968, 0.6083, 0.9867, 0, 0.06689, 0), 
                                                                              .Dim = 3:2, 
                                                                              .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                 "Her2 vs Other(s)", 
                                                                                                 "LumA vs Other(s)"), 
                                                                                               c("AUC", "p-value"))), 
                                                            comp2 = structure(c(0.9983, 0.9631, 0.9954, 0, 4.885e-15, 0), 
                                                                              .Dim = 3:2, 
                                                                              .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                 "Her2 vs Other(s)", 
                                                                                                 "LumA vs Other(s)"), 
                                                                                               c("AUC", "p-value")))), 
                                                proteomics = list(comp1 = structure(c(0.9729, 0.6378, 0.9854, 0, 0.01978, 0), 
                                                                                    .Dim = 3:2, 
                                                                                    .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                       "Her2 vs Other(s)", 
                                                                                                       "LumA vs Other(s)"), 
                                                                                                     c("AUC", "p-value"))), 
                                                                  comp2 = structure(c(0.9886, 0.9383, 0.9956, 0, 1.223e-13, 0), 
                                                                                    .Dim = 3:2, 
                                                                                    .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                       "Her2 vs Other(s)", 
                                                                                                       "LumA vs Other(s)"), 
                                                                                                     c("AUC", "p-value"))))),
                      srbct.splsda = list(Comp1 = structure(c(0.3891, 1, 0.8088, 0.6547, 0.1453, 5.586e-06, 0.0009391, 0.04955), 
                                                            .Dim = c(4L, 2L), 
                                                            .Dimnames = list(c("EWS vs Other(s)", 
                                                                               "BL vs Other(s)", 
                                                                               "NB vs Other(s)", 
                                                                               "RMS vs Other(s)"), 
                                                                             c("AUC", "p-value"))), 
                                          Comp2 = structure(c(1, 1, 0.8791, 0.8081, 5.135e-11, 5.586e-06, 4.89e-05, 9.12e-05), 
                                                            .Dim = c(4L, 2L), 
                                                            .Dimnames = list(c("EWS vs Other(s)", 
                                                                               "BL vs Other(s)", 
                                                                               "NB vs Other(s)", 
                                                                               "RMS vs Other(s)"), 
                                                                             c("AUC", "p-value")))),
                      newdata.splsda = list(Comp1 = structure(c(0.6667, 0.5637), 
                                                              .Dim = 1:2, 
                                                              .Dimnames = list("AF vs BE", 
                                                                               c("AUC", "p-value"))), 
                                            Comp2 = structure(c(0.6667, 0.5637), 
                                                              .Dim = 1:2, 
                                                              .Dimnames =
                                                                  list("AF vs BE",
                                                                       c("AUC", "p-value")))),
                      multilevel.splsda = list(Comp1 = structure(c(0.5024, 0.9976, 1, 0.9603, 0, 0), 
                                                                 .Dim = 3:2, 
                                                                 .Dimnames = list(c("Antecubital_fossa vs Other(s)", 
                                                                                    "Stool vs Other(s)", 
                                                                                    "Subgingival_plaque vs Other(s)"), 
                                                                                  c("AUC", "p-value"))), 
                                               Comp2 = structure(c(1, 1, 1, 0, 0, 0), 
                                                                 .Dim = 3:2, 
                                                                 .Dimnames = list(c("Antecubital_fossa vs Other(s)", 
                                                                                    "Stool vs Other(s)", 
                                                                                    "Subgingival_plaque vs Other(s)"), 
                                                                                  c("AUC", "p-value")))),
                      roc.comp.splsda = list(Comp1 = structure(c(0.863, 2.473e-05), 
                                                               .Dim = 1:2, 
                                                               .Dimnames = list("AF vs BE", 
                                                                                c("AUC", "p-value"))), 
                                             Comp2 = structure(c(0.9981, 7.124e-09), 
                                                               .Dim = 1:2, 
                                                               .Dimnames = list("AF vs BE", 
                                                                                c("AUC", "p-value")))),
                      roc.study.mint.splsda = list(Comp2 = structure(c(1, 0.9028, 0.9889, 4.799e-09, 0.02024, 3.751e-09), 
                                                                     .Dim = 3:2, 
                                                                     .Dimnames = list(c("Fibroblast vs Other(s)",
                                                                                        "hESC vs Other(s)", 
                                                                                        "hiPSC vs Other(s)"), 
                                                                                      c("AUC", "p-value")))),
                      roc.block.splsda = list(miRNA = list(comp1 = structure(c(0.9365, 0.5861, 0.9218, 0, 0.1453, 0), 
                                                                             .Dim = 3:2, 
                                                                             .Dimnames = list(c("Basal vs Other(s)",
                                                                                                "Her2 vs Other(s)", 
                                                                                                "LumA vs Other(s)"), 
                                                                                              c("AUC", "p-value"))), 
                                                           comp2 = structure(c(0.9494, 0.5856, 0.9257, 0, 0.1479, 0), 
                                                                             .Dim = 3:2, 
                                                                             .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                "Her2 vs Other(s)", 
                                                                                                "LumA vs Other(s)"), 
                                                                                              c("AUC", "p-value")))), 
                                              mRNA = list(comp1 = structure(c(0.9937, 0.6206, 0.9918, 0, 0.04144, 0), 
                                                                            .Dim = 3:2, 
                                                                            .Dimnames = list(c("Basal vs Other(s)", 
                                                                                               "Her2 vs Other(s)", 
                                                                                               "LumA vs Other(s)"), 
                                                                                             c("AUC", "p-value"))), 
                                                          comp2 = structure(c(0.9962, 0.5725, 0.9893, 0, 0.2201, 0), 
                                                                            .Dim = 3:2, 
                                                                            .Dimnames = list(c("Basal vs Other(s)", 
                                                                                               "Her2 vs Other(s)", 
                                                                                               "LumA vs Other(s)"), 
                                                                                             c("AUC", "p-value")))), 
                                              proteomics = list(comp1 = structure(c(0.9564, 0.6578, 0.9844, 0, 0.007614, 0), 
                                                                                  .Dim = 3:2, 
                                                                                  .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                     "Her2 vs Other(s)", 
                                                                                                     "LumA vs Other(s)"), 
                                                                                                   c("AUC", "p-value"))), 
                                                                comp2 = structure(c(0.9757, 0.6564, 0.9865, 0, 0.008164, 0), 
                                                                                  .Dim = 3:2, 
                                                                                  .Dimnames = list(c("Basal vs Other(s)", 
                                                                                                     "Her2 vs Other(s)", 
                                                                                                     "LumA vs Other(s)"), 
                                                                                                   c("AUC", "p-value"))))),
                      study.test.mint.splsda = list(Comp2 = structure(c(1, 0.8333, 1, 0.1573, 0.2482, 0.08326), 
                                                                      .Dim = 3:2, 
                                                                      .Dimnames = list(c("Fibroblast vs Other(s)", 
                                                                                         "hESC vs Other(s)",
                                                                                         "hiPSC vs Other(s)"), 
                                                                                       c("AUC", "p-value"))))
                      )